server:
  port: 9090
eureka:
  client:
    service-url:
      ##设置服务注册中心的URL，用于client和server端交流
      defaultZone: http://eer1:9090/eureka/
      #是否将自己注册到Eureka Server,默认为true，由于当前就是server，故而设置成false，表明该服务不会向eureka注册自己的信息
    register-with-eureka: false
    #是否从eureka server获取注册信息，由于单节点，不需要同步其他节点数据，用false
    fetch-registry: false
  instance:
    hostname: peer1        #需要在hosts文件里面配置peer1
spring:
  application:
    name: eureka-server-peer1-v0
